### ISSUE TITLE
Delete button works only by tapping

### ISSUE THREAD

**Issue by isaacvr** [ricky9667/HushKeyboard#47]
When I press the button to delete something in the scramble, the button works, but only if I press it multiple times. It should be more user-friendly if it starts deleting while the key is pressed.

Environment
Platform: Android 13
One UI: 5.1
Hush Keyboard: 0.4.0

**Comment by ricky9667** [comment]
Thanks for letting me know, I'll add some features to make it better. Thanks :)

**Comment by ricky9667** [comment]
I added a feature issue that will address this problem, therefore I'll close this issue first. 
Reference: https://github.com/ricky9667/HushKeyboard/issues/49
